_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 15
                - 16
                - 35
                - 55
            "4": 3.10.12
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 64
close_environment_at_exit:
    value: true
disable_progressbar:
    value: false
discount_factor:
    value: 0.99
environment_info:
    value: episode
experiment:
    value:
        checkpoint_interval: 10000
        directory: results/2025-07-01_161512_f1tenth_experiment
        experiment_name: f1tenth_experiment
        store_separately: false
        wandb: true
        wandb_kwargs:
            name: experiment-test
            project: f1tenth-rl
            tags: []
        write_interval: 10000
        writer: wandb
exploration:
    value:
        final_epsilon: 0.1
        initial_epsilon: 1
        timesteps: 50000
gradient_steps:
    value: 1
headless:
    value: true
learning_rate:
    value: 0.001
learning_rate_scheduler:
    value: null
learning_starts:
    value: 0
mixed_precision:
    value: false
polyak:
    value: 0.005
q_network:
    value:
        backbone: |-
            BasicLSTMNet(
              (lstm): LSTM(1081, 128)
              (actor): Linear(in_features=128, out_features=2, bias=True)
              (critic): Linear(in_features=128, out_features=1, bias=True)
            )
random_timesteps:
    value: 0
rewards_shaper:
    value: null
state_preprocessor:
    value: null
stochastic_evaluation:
    value: false
target_q_network:
    value:
        backbone: |-
            BasicLSTMNet(
              (lstm): LSTM(1081, 128)
              (actor): Linear(in_features=128, out_features=2, bias=True)
              (critic): Linear(in_features=128, out_features=1, bias=True)
            )
target_update_interval:
    value: 10
timesteps:
    value: 10000000
update_interval:
    value: 1
